# Generated by Django 4.2.1 on 2023-05-17 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aparato_electro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especificacion', models.CharField(help_text='Ingrese especificacion', max_length=100)),
                ('nombre', models.CharField(help_text='Ingrese nombre', max_length=36)),
                ('aparatoE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aparato_electro.aparatoe')),
            ],
            options={
                'verbose_name': 'Nombre',
                'verbose_name_plural': 'Nombres',
            },
        ),
    ]
