# Generated by Django 4.2.1 on 2023-05-17 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('componente', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='componente',
            options={'verbose_name': 'Componente', 'verbose_name_plural': 'Componentes'},
        ),
    ]
